version: '3'

services:
  dht22-monitor:
    build: .
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/gpiochip0:/dev/gpiochip0"
    volumes:
      - .env:/app/.env
    restart: unless-stopped
    network_mode: "host"